#!/bin/bash
#
#
export PYVERSION=$(cat ./ovispyversion)
export COLLVERSION=$(cat ./ovisversion)
SCL=sandia-nosos-ovis_${COLLVERSION}
packing=v4.toss3.nosos.unstable
PART=PAPI
papiver=papi-6.0.0
papitar=${papiver}.tar.gz
PAPIURL=http://icl.utk.edu/projects/papi/downloads/$papitar
shasum="3442709dae3405c2845b304c06a8b15395ecf4f3899a89ceb4d715103cb4055f"

if test -n "$MODULEPATH"; then
	module purge
fi
. ../support/package-functions

dn=$(pwd)
specdir=$dn
bn=$(basename $dn)
specfile=papi.spec
if test "$bn" = "$packing" -a -f $specfile; then
	: in the right place
else
	echo This must be run from $packing, which should be clean and at any rate will be overwritten.
	exit 1
fi

/bin/rm -rf $PART
mkdir $PART
cd $PART
wget $PAPIURL
dlsum=$(sha256sum $papitar| cut -f1 -d" ")
if test "$dlsum" != "$shasum"; then
	echo "download of $PAPIURL failed"
	echo $dlsum
	echo $shasum
	exit 1
fi
mkdir -p $PART/$packing/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
cp $papitar $PART/$packing/SOURCES && \
echo "rpmbuild============================" && \
rpmbuild -vv \
 --define "_topdir `pwd`/$PART/$packing" \
 --noclean \
 -ba $specdir/$specfile && \
touch completed
if ! test -f completed; then
	echo FAIL
else
	echo PASS
	cd $dn
	echo the droids you seek may be:
	find $PART -name '*.rpm'
fi
