#!/bin/bash
#
#
packing=cle5.unstable
ovis_branch=master
sos_branch=master
NetworkRequires=gitlab.opengridcomputing.com
SOSREPO=gitlab@gitlab.opengridcomputing.com:tom/SOS.git
OVISREPO=gitlab@gitlab.opengridcomputing.com:ovis/ovis.git

. ../support/package-functions

CFLAGS='-g -O0 -DDEBUG -Werror -Wl,-z,defs -DLDMSD_UPDATE_TIME'
prefix=/usr
LOCAL_OPTS="
--with-libevent=/home/gentile/Build/libevent-2.0_build
--with-cray-nvidia-inc=/home/gentile/Source/old/gdk_linux_amd64_release/nvml
"

PACK_OPTS="
--disable-rpath
--disable-static
--prefix=$prefix
--with-pkglibdir=ovis-ldms
"
DOC_OPTS="
--enable-doc
--enable-doc-html
"
SECURITY_OPTS="
--enable-ovis_auth
--enable-ssl
"
NETWORK_OPTS="
--enable-ovis_event
--enable-zap
--enable-sock
--disable-mmap
"
CRAY_LOCATIONS="
--with-rca=/opt/cray/rca/default/
--with-krca=/opt/cray/krca/default
--with-cray-hss-devel=/opt/cray-hss-devel/default
"
IFACE_OPTS="
--disable-swig
--disable-readline
--enable-ldms-python
--disable-python
--disable-libgenders
--disable-yaml
"
BALER_OPTS="
--disable-baler
"
STORE_OPTS="
--disable-sos
--disable-flatfile
--enable-csv
--enable-store
--disable-rabbitv3
"
SAMPLER_OPTS="
--disable-jobid
--enable-tsampler
--enable-cray_power_sampler
--disable-perfevent
--disable-papi
--disable-perf
--disable-sensors
--disable-meminfo
--disable-array_example
--disable-procinterrupts
--disable-procnetdev
--disable-procnfs
--disable-procsensors
--disable-procstat
--disable-vmstat
--disable-procdiskstats
--disable-atasmart
--disable-hadoop
--disable-generic_sampler
--disable-switchx
--enable-cray_system_sampler
--enable-gemini-gpcdr
--enable-aries-gpcdr
--enable-kgnilnd
--disable-gpcdlocal
--disable-aries-mmr
--enable-ugni
--enable-lustre
"
allconfig="$PACK_OPTS $SECURITY_OPTS $NETWORK_OPTS $IFACE_OPTS $BALER_OPTS $STORE_OPTS $SAMPLER_OPTS $CRAY_LOCATIONS $LOCAL_OPTS"

if ! pack_prechecks "$allconfig"; then
	echo "Check dependencies listed above, install needed packages, and try again"
	exit 1
fi

dn=$(pwd)
bn=$(basename $dn)
if test "$bn" = "$packing" -a -f ovis.spec.in; then
	: in the right place
else
        echo This must be run from $packing, which should be clean and at any rate will be overwritten.
        exit 1
fi

specdir=$dn
#GPTAR=gpcd-support.tar
#SOSTAR=sos.tar
#if ! test -f $SOSTAR; then
#        echo archive $SOSTAR must be in spec dir
#        exit 1
#fi
#if ! test -f $GPTAR; then
#        echo archive $GPTAR must be in spec dir
#        exit 1
#fi
/bin/rm -rf ovis
if ! git clone $OVISREPO ovis; then
	echo cannot checkout ovis.
	exit 1
fi

cd ovis
if ! git checkout $ovis_branch; then
	echo cannot checkout ovis branch $ovis_branch.
	exit 1
fi
VERSION=$(pack_get_ac_version configure.ac)
PACKAGE=$(pack_get_ac_name configure.ac)
# Find SHA of latest checkin someone tagged
COMMIT_ID="$(git log -1 --pretty="%H")"
BASE_COMMIT_ID="$(git rev-parse $ovis_branch)"

# Get most recent tag id for this branch
TAG_ID="$(git describe --tags --abbrev=0)"
TARGET=${PACKAGE}-${VERSION}.tar
REPO_DIR=`pwd`
OUTPUT_DIR=`pwd`/Tars
# Create output dir
mkdir -p $OUTPUT_DIR
# populate outdir inputs
git archive --prefix=${PACKAGE=}-${VERSION}/ $COMMIT_ID --format=tar --output=${OUTPUT_DIR}/$TARGET
sleep 0.1
#cp ../$GPTAR $OUTPUT_DIR
#cp ../$SOSTAR $OUTPUT_DIR

cd $OUTPUT_DIR

# Untar archive
echo "Untarring archive"
tar xf $TARGET && \
(cd ${PACKAGE}-${VERSION} && \
: tar xf ../$SOSTAR && \
: tar xf ../$GPTAR && \
mkdir -p gpcd-support/m4 && \
./autogen.sh)
if ! test -f ${PACKAGE}-${VERSION}/configure; then
	echo "unable to generate ovis build files"
	exit 1
fi

# Tar back up excluding unwanted files and dirs
echo "tarring archive with excludes from "
echo "$REPO_DIR/util/tar-excludes.txt"
TAR_OPTS="-X $REPO_DIR/util/tar-excludes.txt"
tar czf $TARGET.gz $TAR_OPTS ${PACKAGE}-${VERSION}

echo "Relocating cruft"
rm -rf old
mkdir old
mv -f ${PACKAGE}-${VERSION} $TARGET $SOSTARGET old
specfile=tmp-ovis-${packing}.spec
tar zxf $TARGET.gz && \
cd ${PACKAGE}-${VERSION} && \
echo "================ configure for $packing rpms =============" && \
./configure CFLAGS="$CFLAGS" CC=gcc CXX=g++ $allconfig && \
echo "============================= make $packing rpms =============" && \
make dist-gzip && \
mkdir -p $packing/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
cp $TARGET.gz $packing/SOURCES && \
./config.status --file=-:$specdir/ovis.spec.in | \
./ldms/config.status --file=-:- | \
./lib/config.status --file=$specdir/tmp-ovis-${packing}.spec:- && \
if test -f baler/config.status; then
	./baler/config.status --file=$specdir/baler-ovis-${packing}.spec:$specdir/tmp-ovis-${packing}.spec
	specfile=baler-ovis-${packing}.spec
fi && \
if test -f sos/config.status; then
	./sos/config.status --file=$specdir/ovis-${packing}.spec:$specdir/$specfile
	specfile=ovis-${packing}.spec
else
	cat $specdir/$specfile | sed -e 's/^@ENABLE_/#@ENABLE_/g' > $specdir/ovis-${packing}.spec
	specfile=ovis-${packing}.spec
fi && \
rpmbuild -v --define "_topdir `pwd`/$packing" -ba $specdir/$specfile && \
touch completed
if ! test -f completed; then
	echo FAIL
else
	echo PASS
	cd $dn
	echo the droids you seek may be:
	find . -name '*.rpm'
fi
