#!/bin/bash
#
#
export PYVERSION=$(cat ./ovispyversion)
SCL=sandia-ovis_python2_$PYVERSION
packing=v43.toss3.opt.stable
pypack=numpy

PART=NUMPY
NetworkRequires=github.com
tar=numpy-1.14.6.tar.gz

if test -n "$MODULEPATH"; then
	module purge
	# module load ovis_python2/4.3
fi
. ../support/package-functions

dn=$(pwd)
specdir=$dn
bn=$(basename $dn)
specfile=toss-scl-python2-$pypack.spec
if test "$bn" = "$packing" -a -f $specfile; then
	: in the right place
else
	echo This must be run from $packing, which should be clean and at any rate will be overwritten.
	exit 1
fi
rm -f $PART $tar
wget https://github.com/numpy/numpy/releases/download/v1.14.6/numpy-1.14.6.tar.gz && \
mkdir -p $PART/$packing/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
cp $tar $specfile $PART/$packing/SOURCES/ && \
(cd $PART && \
rm -f completed && \
rpmbuild -v \
 --define "_topdir `pwd`/$packing" \
 --define "scl $SCL" \
 --define "scl_name_version $PYVERSION" \
 -ba $specdir/$specfile && \
touch completed)
if ! test -f $PART/completed; then
	echo FAIL
else
	echo PASS
	cd $dn
	echo the droids you seek may be:
	find $PART -name '*.rpm'
fi
