#!/bin/bash
#
#
export PYVERSION=$(cat ./ovispyversion)
export COLLVERSION=$(cat ./ovisversion)
packing=v4.atse.nosos.unstable
PART=LLNLLUSTRE
llnlver=ldms-plugins-llnl-1.5
llnltar=${llnlver}.tar.gz
LLNLLUSTREURL=https://github.com/LLNL/ldms-plugins-llnl/releases/download/1.5/ldms-plugins-llnl-1.5.tar.gz
shasum="1900d539f6910d6f59deb45219fc2dd5f5f8efc977e3991729166902239f9811"

if test -n "$MODULEPATH"; then
	module purge
fi
. ../support/package-functions

dn=$(pwd)
specdir=$dn
bn=$(basename $dn)
specfile=llnllustre.spec
if test "$bn" = "$packing" -a -f $specfile; then
	: in the right place
else
	echo This must be run from $packing, which should be clean and at any rate will be overwritten.
	exit 1
fi

/bin/rm -rf $PART
mkdir $PART
cd $PART
wget $LLNLLUSTREURL
dlsum=$(sha256sum $llnltar| cut -f1 -d" ")
if test "$dlsum" != "$shasum"; then
	echo "download of $LLNLLUSTREURL failed"
	echo $dlsum
	echo $shasum
	exit 1
fi
mkdir -p $PART/$packing/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
cp $llnltar $PART/$packing/SOURCES && \
echo "rpmbuild============================" && \
rpmbuild -vv \
 --define "_topdir `pwd`/$PART/$packing" \
 --noclean \
 -ba $specdir/$specfile && \
touch completed
if ! test -f completed; then
	echo FAIL
else
	echo PASS
	cd $dn
	echo the droids you seek may be:
	find $PART -name '*.rpm'
fi
